### ISSUE TITLE
Have you got the tiktok API working?

### ISSUE THREAD

**Issue by sabitm** [PavlenkoDR/XamarinStudents#1]
I'm searching through some tiktok API on github and stumbled upon this repo specifically on `Hometasks/HW5/api.py` file. Have you got it working? I noticed there are some code missing for `Helper` class when I try it. Thanks and appreciates any answer!

**Comment by PavlenkoDR** [comment]
Hello. api.py not mine and HW5 is draft howmework for students. I am still work on it. You can check how get some data with tiktok api in
https://github.com/PavlenkoDR/TikTokDownloader/blob/2a7e45f1a31e8d32da1c67219d981a8b5eeb44d9/TikTokDownloader/TikTokDownloader/ContentDownloadManager.cs#L174

**Comment by PavlenkoDR** [comment]
For example https://api16-normal-c-useast1a.tiktokv.com/aweme/v1/feed/?aweme_id=6930858277987241217
